version: '3'

services:
  web:
    image: php:7.4-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  db_data:
